theme: jekyll-theme-cayman
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samian LOD Documentation
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Diese Seite soll unsere Präsentation graphisch unterstützen. Auf diese Weise
  sind Darstellung und Aufbau einer Seite mit Jekyll anschaulich und nachvollziehbar.
baseurl: "samian-lod" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gitlab_username:  pages

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]
