name: Java CI

on: [push]

jobs:
    
  ontdocI:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc I      
    with: 
          rdffilepath: data/loc_discoverysite_1.ttl data/loc_kilnregion_1.ttl data/loc_productioncentre_1.ttl data/loc_repositorylocation_1.ttl data/placeasaconcept_1.ttl
          docpath: docs/
          prefixns: http://data.archaeology.link/data/samian/
          prefixnsshort: ars
          indexpages: true
          metadatatable: true
          createcollections: true
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: ontdoc/

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out main
        uses: actions/checkout@main
        with:
          fetch-depth: 1
           sudo apt-get install python3 python3-pip -y   
      - name: Create Ontology Documentation 🔧
        run: |
             sudo apt-get install python3 python3-pip -y   
             pip3 install pylode
             mkdir docs
             cd docs
             python3 -m pylode -o ontology.html ../ontology/ontology.ttl
      - name: 🧪 Build and deploy
        uses: victoriadrake/jekyll-cd@master
