name: Java CI

on: [push]

jobs:
    
  ontdocI:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    name: Ontdoc I      
    with: 
          rdffilepath: data/loc_discoverysite_1.ttl data/loc_kilnregion_1.ttl data/loc_productioncentre_1.ttl data/loc_repositorylocation_1.ttl data/placeasaconcept_1.ttl
          docpath: docs/
          prefixns: http://data.archaeology.link/data/samian/
          prefixnsshort: ars
          indexpages: true
          metadatatable: true
          createcollections: true
          createnonNSPages: true
          createVOWL: true
          preferredlang: en
          ghpages: true
          ghpagesfolder: /
